[build-system]
requires = [ "setuptools",]
build-backend = "setuptools.build_meta"

[project]
name = "bcs_kedro"
readme = "README.md"
dynamic = [ "dependencies", "version",]

[project.scripts]
bcs-kedro = "bcs_kedro.__main__:main"

[tool.kedro]
package_name = "bcs_kedro"
project_name = "bcs-kedro"
kedro_init_version = "0.19.7"
tools = [ "Custom Logging", "Data Structure", "Kedro Viz",]
example_pipeline = "True"
source_dir = "src"

[project.entry-points."kedro.hooks"]

[tool.setuptools.dynamic.dependencies]
file = "requirements.txt"

[tool.setuptools.dynamic.version]
attr = "bcs_kedro.__version__"

[tool.setuptools.packages.find]
where = [ "src",]
namespaces = false

[tool.kedro_telemetry]
project_id = "f08804a3903e48758fc60513da94caf7"
